runtime: aspnetcore
env: flex

instance_class: F2

entrypoint: dotnet OnDaGo.API.dll

env_variables:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__MongoDb: "mongodb+srv://ondagoadmin:ondagoit09@ondago.jiv6m.mongodb.net/?retryWrites=true&w=majority&appName=OnDaGo"
  Smtp__Host: "smtp.gmail.com"
  Smtp__Port: "8274661"
  Smtp__EnableSsl: "true"
  Smtp__Username: "email"
  Smtp__Password: "key"

resources:
  cpu: 1
  memory_gb: 2

# allow_unauthenticated: true

network:
  forwarded_ports:
    - 5147  # Port from your app configuration

health_check:
  enable_health_check: true
  check_interval_sec: 10  # Interval in seconds
  timeout_sec: 5          # Timeout in seconds
  unhealthy_threshold: 3
  healthy_threshold: 1
